ALTER TABLE invoice_lines ADD COLUMN tax_rate NUMERIC(15, 4) NOT NULL DEFAULT 0;
ALTER TABLE invoice_lines ADD COLUMN tax_amount NUMERIC(15, 4) NOT NULL DEFAULT 0;
ALTER TABLE invoice_lines ADD COLUMN net_price NUMERIC(15, 4) NOT NULL DEFAULT 0;
ALTER TABLE invoices ADD COLUMN total_tax NUMERIC(15, 4) NOT NULL DEFAULT 0;
